Added PHP 8.0 support #4
mezzio/mezzio-laminasviewrenderer pull request #5
Opened 2020-11-04 08:48 UTC by svycka

Q | A
-- | --
New Feature | yes

Summary
To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [x] Modify composer.json to provide support for PHP 8.0 by adding the constraint ~8.0.0
- [x]  Modify composer.json to drop support for PHP less than 7.3
- [x]  Modify composer.json to implement phpunit 9.3 which supports PHP 7.3+
- [x]  Modify .travis.yml to ignore platform requirements when installing composer dependencies (simply add --ignore-platform-reqs to COMPOSER_ARGS env variable)
- [x]  Modify .travis.yml to add PHP 8.0 to the matrix (NOTE: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [x]  Modify source code in case there are incompatibilities with PHP 8.0

closes #4

2020-11-04 08:51 UTC, samsonasik commented on test/LaminasViewRendererTest.php
> +        $r = new \ReflectionProperty($view, 'renderer');
can be moved to use statement

2020-11-04 09:43 UTC, svycka commented
Coverage decreased but I can't see why I guess because of PHPUnit and coverage update because it was not covered before but it was reported as covered for some reason as I understand

2020-11-04 12:15 UTC, svycka commented
Added test to cover uncovered line, coverage increased but coveralls still complains not sure why :)

2020-11-04 13:17 UTC, froschdesign requested changes
A big thank you for your contribution! 👍 

I only added some small comments and suggestions. Thanks in advance!

2020-11-04 13:17 UTC, froschdesign commented on .travis.yml
> +    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
The new parameter is only needed for the nightly version. Please move this to the related section.

2020-11-04 13:17 UTC, froschdesign commented on .travis.yml
>          - DEPS=lowest
```suggestion
    - php: nightly
      env:
        - DEPS=lowest
        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
```

2020-11-04 13:17 UTC, froschdesign commented on .travis.yml
>          - DEPS=latest
```suggestion
    - php: nightly
      env:
        - DEPS=latest
        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
```

2020-11-04 13:17 UTC, froschdesign commented on phpunit.xml.dist
> +<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" bootstrap="./vendor/autoload.php" colors="true" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd">
In the Composer configuration PHPUnit is set to version 9.4.x but the XML schema definition of version 9.3 is used here.
Therefore I would suggest the following:
```suggestion
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" bootstrap="./vendor/autoload.php" colors="true" xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd">
```

2020-11-04 13:17 UTC, froschdesign commented on test/LaminasViewRendererTest.php
> +
Maybe I missed something, but why is this trait necessary here?

2021-01-23 16:47 UTC, adamturcsan commented
@svycka @froschdesign May I help you somehow to finish this PR?

2021-03-24 07:06 UTC, froschdesign commented on .travis.yml
> +    - php: nightly
```suggestion
    - php: 8.0
```

2021-03-24 07:06 UTC, froschdesign commented on .travis.yml
> +    - php: nightly
```suggestion
    - php: 8.0
```

2021-03-24 07:06 UTC, froschdesign commented on .travis.yml
> +        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
```suggestion
```

2021-04-19 22:17 UTC, weierophinney commented
Closing in favor of #6, which also updated us to github actions (allowing us to finish validation of testing).

2021-04-19 22:17 UTC, closed without merging