Support `psr/container:^2.0`
mezzio/mezzio-laminasviewrenderer pull request #55
Opened 2023-11-06 14:51 UTC by pascalheidmann

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

Adding support for `psr/container:^2.0` in composer.json (its basically the same as 1.0 but with return types)

2023-11-06 15:36 UTC, Ocramius requested changes
According to CI, `psr/container:^2` never got installed while testing this?

2023-11-06 15:37 UTC, Ocramius commented
Same as https://github.com/mezzio/mezzio-laminasviewrenderer/pull/23#pullrequestreview-1109391641 BTW

2023-11-11 23:47 UTC, pascalheidmann commented
@Ocramius yeah saw it only afterwards.. Basically wont work until servicemanager 4 will be released? Are you the maintainer of that package too or is it up to @boesing?

2025-11-24 15:18 UTC, gsteel commented
This is resolved in #74 with the upgrade of `laminas-view` and `laminas-servicemanager`

2025-11-24 15:18 UTC, closed without merging